---
# tasks file for appache
- name: install Appache
  yum:
    name: "{{pkg_name}}"
    state: present
- name: copy index file
  copy:
    src: files/index.html
    dest: "{{dest_folder}}"
    remote_src: no
  notify: restart apache